name = "NewickTree"
uuid = "b0a14db8-6308-4ebc-8917-f72cd81f5094"
authors = ["arzwa <arzwa@psb.vib.ugent.be>"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"

[compat]
julia = "^1"
DataStructures = "0.17.8"
