name: build

on: 
  push: 
    branches:
      - master
      - dev
    pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.version == 'nightly' }}
    strategy:
      matrix:
        version:
          - '1.6'
          - 'nightly'
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/julia-buildpkg@latest
        #- uses: julia-actions/julia-runtest@latest
      - run: |
          julia --color=yes --check-bounds=yes --inline=yes --project=@. --depwarn=yes -e '
            using Pkg; Pkg.test(coverage=false)'
